global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: alunos
    static_configs:
      - targets: ['alunos:8000']

  - job_name: auth
    static_configs:
      - targets: ['auth:8000']

  - job_name: conteudos
    static_configs:
      - targets: ['conteudos:8000']

  - job_name: exercicios
    static_configs:
      - targets: ['exercicios:8000']

  - job_name: trilhas
    static_configs:
      - targets: ['trilhas:8000']
