events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # ── Serviços backend ─────────────────────────────────────────────────
        location /auth/ {
            proxy_pass         http://auth:8000/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /alunos/ {
            proxy_pass         http://alunos:8000/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /exercicios/ {
            proxy_pass         http://exercicios:8000/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /trilhas/ {
            proxy_pass         http://trilhas:8000/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        location /conteudos/ {
            proxy_pass         http://conteudos:8000/;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
        }

        # ── Frontend estático ─────────────────────────────────────────────────
        location / {
            root  /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
